# Generated by Django 4.2.3 on 2023-08-07 10:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('image', models.ImageField(blank=True, default='/director/default.png', null=True, upload_to='./director/')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('position', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('image', models.ImageField(default='/news/news.png', upload_to='./news/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Malumot')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Malumot')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Malumot')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Malumot')),
                ('page_name', models.CharField(max_length=300, verbose_name='Page Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('image', models.ImageField(blank=True, default='/director/default.png', null=True, upload_to='./director/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
