# Generated by Django 4.2.3 on 2023-07-10 08:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Malumot')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Malumot')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Malumot')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Malumot')),
                ('page_name', models.CharField(max_length=300, verbose_name='Page Name')),
            ],
        ),
    ]
