# Generated by Django 4.2.3 on 2023-07-11 05:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('image', models.ImageField(blank=True, default='/director/default.png', null=True, upload_to='./director/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Malumot')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lavozimi')),
            ],
        ),
    ]
